### ISSUE TITLE
aro-machinesets chart not published in https://rh-mobb.github.io/helm-charts/!

### ISSUE THREAD

**Issue by jtudelag** [rh-mobb/helm-charts#36]
Hey, 

https://rh-mobb.github.io/helm-charts/ is missing aro-machineset chart, while that is being referenced in this piece of doc: https://mobb.ninja/docs/aro/add-infra-nodes/

Cheers!

**Comment by paulczar** [comment]
Hi, I believe this should be fixed now!  Looks like the automation involved in releasing the chart didn't fire for it, so I just bumped its version and released it.
